// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2xYnKs3swvN2ieBdjeWyNHXXh0pLTVXs',
    appId: '1:295242720949:web:c12159dd55da0797cc40fc',
    messagingSenderId: '295242720949',
    projectId: 'campus-conn',
    authDomain: 'campus-conn.firebaseapp.com',
    storageBucket: 'campus-conn.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5uUd8n1QZ2QJPoj-7gRN-vg9dYMXEtXM',
    appId: '1:295242720949:android:470ea5e6c83ba19dcc40fc',
    messagingSenderId: '295242720949',
    projectId: 'campus-conn',
    storageBucket: 'campus-conn.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBU7j7P82QtklclYgteCpN_gtf8BrPEJfY',
    appId: '1:295242720949:ios:ccd8bb2644e049b9cc40fc',
    messagingSenderId: '295242720949',
    projectId: 'campus-conn',
    storageBucket: 'campus-conn.firebasestorage.app',
    iosBundleId: 'com.example.campusConn',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBU7j7P82QtklclYgteCpN_gtf8BrPEJfY',
    appId: '1:295242720949:ios:ccd8bb2644e049b9cc40fc',
    messagingSenderId: '295242720949',
    projectId: 'campus-conn',
    storageBucket: 'campus-conn.firebasestorage.app',
    iosBundleId: 'com.example.campusConn',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD2xYnKs3swvN2ieBdjeWyNHXXh0pLTVXs',
    appId: '1:295242720949:web:72cc795c94f4f7c8cc40fc',
    messagingSenderId: '295242720949',
    projectId: 'campus-conn',
    authDomain: 'campus-conn.firebaseapp.com',
    storageBucket: 'campus-conn.firebasestorage.app',
  );
}
